version: "2"

services:
  server:
    image: node:10
    restart: always
    user: node
    tty: true
    working_dir: /home/node/app
    command: /usr/local/bin/start-server.sh
    volumes:
      - ./server:/home/node/app
      - ./docker/scripts/start-server.sh:/usr/local/bin/start-server.sh
    expose:
      - 3033 # Backend server (feathersjs)
    ports:
      - 3033:3033

  web:
    image: node:10
    restart: always
    user: node
    tty: true
    working_dir: /home/node/app
    command: /usr/local/bin/start-web.sh
    volumes:
      - ./web:/home/node/app
      - ./docker/scripts/start-web.sh:/usr/local/bin/start-web.sh
    expose:
      - 3003 # Frontend server dev (react)
    ports:
      - 3003:3003

  mongo:
    image: mongo:4
    restart: always
    volumes:
      - ./docker/data/mongo:/data/db
    expose:
      - 27017

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    expose:
      - 8081
    ports:
      - 8083:8081

  mail-server:
    image: mailhog/mailhog
    restart: always
    expose:
      - 1025 # SMTP Server to send mail
      - 8025 # Web ui to check mail
    ports:
      - 8023:8025

  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - ./docker/data/redis:/data
    expose:
      - 6379

  swagger:
    image: swaggerapi/swagger-editor
    expose:
      - 8080
    ports:
      - 8003:8080
